server:
  port: 8082
  contextPath: /

spring:
  application:
    name: greeting-service
  security:
    ignored: /**
    user:
      name: admin
      password: password

eureka:
  instance:
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:password@localhost:8061/eureka/

logging:
  level:
    greetings: DEBUG
